test gagal

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -97,10 +97,10 @@ jobs:
   laravel_notification:
     name: Laravel Notification
     runs-on: ubuntu-latest
-    needs: 
+    needs:
       - laravel_build
       - laravel_test
-  
+
     steps:
       - name: Check if laravel_build job was successful
         env:
@@ -110,17 +110,29 @@ jobs:
             echo "Laravel build job was successful."
           else
             echo "Laravel build job failed."
-            exit 1 # Keluar dengan status gagal
+            echo "build_status=failure" >> $GITHUB_OUTPUT
           fi
-  
+
       - name: Check if laravel_test job was successful
         env:
           TEST_STATUS: ${{ needs.laravel_test.result }}
+          BUILD_STATUS: ${{ needs.laravel_build.result }}
         run: |
           if [ "$TEST_STATUS" == "success" ]; then
             echo "Laravel test job was successful."
           else
             echo "Laravel test job failed."
-            exit 1 # Keluar dengan status gagal
+            echo "test_status=failure" >> $GITHUB_OUTPUT
           fi
+
+      - name: Finalize Notification
+        if: ${{ needs.laravel_build.result != 'cancelled' && needs.laravel_test.result != 'cancelled' }}
+        run: |
+          if [ "${{ steps.Check-if-laravel-build-job-was-successful.outputs.build_status }}" == "failure" ] || [ "${{ steps.Check-if-laravel-test-job-was-successful.outputs.test_status }}" == "failure" ]; then
+            echo "At least one job failed."
+            exit 1
+          else
+            echo "All jobs were successful."
+          fi
+        id: finalize-notification
   
