test berhasil

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -63,7 +63,7 @@ jobs:
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
         with:
-          php-version: "8.2" # Sesuaikan dengan versi PHP yang digunakan dalam proyek Laravel 11
+          php-version: "8.2"
 
       - name: Install dependencies
         run: composer install --no-ansi --no-interaction --no-progress --optimize-autoloader
@@ -80,16 +80,13 @@ jobs:
       - name: Run Migration Database
         run: php artisan migrate:fresh --seed
 
-      # - name: Install Breeze
-      #   run: php artisan breeze:install --no-interaction
-
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
-          node-version: "20" # Atur versi Node.js sesuai kebutuhan Anda
+          node-version: "20"
 
       - name: Install Node.js dependencies
-        run: npm install # Atau yarn install jika Anda menggunakan Yarn
+        run: npm install
 
       - name: Build Node.JS
         run: npm run build
@@ -100,36 +97,17 @@ jobs:
   laravel_notification:
     name: Laravel Notification
     runs-on: ubuntu-latest
-    needs: 
-      - laravel_test
+    needs:
       - laravel_build
-
+      - laravel_test
+  
     steps:
-      - name: Check if laravel_build job was successful
-        env:
-          JOB_STATUS: ${{ needs.laravel_build.result }}
+      - name: Check previous job status
         run: |
-          if [ "$JOB_STATUS" == "success" ]; then
-            echo "Laravel test job was successful."
+          if [ "${{ needs.laravel_build.result }}" == 'success' ] && [ "${{ needs.laravel_test.result }}" == 'success' ]; then
+            echo "All previous jobs were successful."
+          else
+            echo "At least one previous job failed."
+            exit 1
           fi
-      - name: Check if laravel_build job was failure
-        env:
-          JOB_STATUS: ${{ needs.laravel_build.result }}
-        run: |
-          if [ "$JOB_STATUS" == "failure" ]; then
-            echo "Laravel test job was failure."
-          fi
-      - name: Check if laravel_test job was successful
-        env:
-          JOB_STATUS: ${{ needs.laravel_test.result }}
-        run: |
-          if [ "$JOB_STATUS" == "success" ]; then
-            echo "Laravel test job was successful."
-          fi
-      - name: Check if laravel_test job was failure
-        env:
-          JOB_STATUS: ${{ needs.laravel_test.result }}
-        run: |
-          if [ "$JOB_STATUS" == "failure" ]; then
-            echo "Laravel test job was failure."
-          fi
+  
